version: '3'

services:
  redis:
    image: redis:latest
    networks:
      - stdweb-net

  stdweb:
    build: .
    networks:
      - stdweb-net
    ports:
      - "8234:8000"
    volumes:
      - ./data:/opt/stdweb/data/
      - ./tasks:/opt/stdweb/tasks/
      - ./index-data:/usr/local/astrometry/data
      
networks:
  stdweb-net:
    driver: bridge
