version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always

  stdweb:
    container_name: stdweb
    build: .
    restart: always
    ports:
      - "8123:8000"
      - "8124:8888"
    volumes:
      - ./data:/opt/stdweb/data/
      - ./tasks:/opt/stdweb/tasks/
      - ./index-data:/usr/local/astrometry/data/
      - ./notebooks:/opt/notebooks
    command: ./start.sh
