version: '3'

services:
  redis:
    image: redis:latest
    networks:
      - stdweb-net

  stdweb:
    build: .
    networks:
      - stdweb-net
    ports:
      - "8234:8000"
    volumes:
      - ./data:/opt/stdweb/data/
      - ./tasks:/opt/stdweb/tasks/
      - ./index-data:/usr/local/astrometry/data
    command: >
      /usr/bin env bash watchmedo auto-restart -d stdweb -p '*.py' --ignore-patterns='*/.*' -- python3 -m celery -- -A stdweb worker --loglevel=info > watchmedo.log 2>&1 &
      /usr/bin env bash python manage.py runserver 0.0.0.0:8000
      
networks:
  stdweb-net:
    driver: bridge
